# Generated by Django 2.1.3 on 2018-11-21 06:29

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(max_length=255, storage=upload.models.ImageFileStorage(), upload_to='shop/img/'),
        ),
    ]
